[Interface]
PrivateKey = iBhDlREvgJQXok05gYu1FP1qsIg7CU2dXUZAyl0/LkM=
Address = 10.200.200.2/32
#
# DNS is intentionally omitted for containerized agents to avoid requiring
# `resolvconf` inside the image. The tunnel can still establish without it.

[Peer]
PublicKey = DDCX+EV1SAWRuyY6DOACg4WFtJ3u8TdEQiqpesGlEl4=
PresharedKey = hMSBO71SeQ4Zq3mjuaKOY6MfLtRwR4xN96dEYXdavm4=
Endpoint = wireguard:51820
AllowedIPs = 10.200.200.0/24
PersistentKeepalive = 25
