[Interface]
PrivateKey = iBhDlREvgJQXok05gYu1FP1qsIg7CU2dXUZAyl0/LkM=
Address = 10.200.200.2/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = DDCX+EV1SAWRuyY6DOACg4WFtJ3u8TdEQiqpesGlEl4=
PresharedKey = hMSBO71SeQ4Zq3mjuaKOY6MfLtRwR4xN96dEYXdavm4=
Endpoint = 127.0.0.1:51820
AllowedIPs = 10.200.200.0/24
PersistentKeepalive = 25
