[default]
elasticsearch=http://seraph-elasticsearch:9200
rotateIndex=daily
passwordSecret=metatron_arkime_lab_secret_2026
httpRealm=Metatron-Lab
interface=br-676f8b6eaea8;wlp0s20f3;any
pcapDir=/opt/arkime/raw
maxFileSizeG=4
tcpTimeout=300
tcpSaveTimeout=600
udpTimeout=30
icmpTimeout=10
maxPacketsInQueue=200000
dbBulkSize=200000
compressES=false
dropUser=root
dropGroup=root

# Capture settings
packetThreads=2
rulesFiles=
ja3Strings=true
snapLen=65535
bufferSize=104857600

# Viewer settings
viewPort=8005
viewHost=0.0.0.0

# Tag sessions
tags=metatron-lab;seraph-evidence
