"""
Canary Replay Verification — Rev14 AAB
========================================
Extracts canary IDs from closed-loop transcript router responses and simulates
their external reuse through Seraph's canary verification endpoint.

A passing verification means:
  - The canary ID was generated by the mirror-world poison layer
  - Seraph detects the reuse and fires an alert
  - The canary ID does NOT map to any real-world credential or token

Usage:
    from tests.adversarial.canary_replay import run_canary_replay_verification
    result = run_canary_replay_verification(records, client=harness.client)
    print(result["verified"], result["alert_rate"])

The ``client`` must support ``client.post(path, json=payload)`` returning a
response with ``.status_code`` and ``.json()`` — compatible with both
``fastapi.testclient.TestClient`` and the ``_HttpxClient`` adapter in
``run_live_aab.py``.
"""
from __future__ import annotations

import re
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

# Canary IDs follow the pattern produced by AdversarialHarness._canary_tracking():
#   canary-{20-hex-chars}
_CANARY_PATTERN = re.compile(r'\bcanary-[0-9a-f]{20}\b')

# Endpoint where Seraph should accept canary-reuse probes.
# Falls back gracefully if the endpoint doesn't exist (returns error flag only).
_CANARY_VERIFY_PATH = "/deception/canary/verify"


def extract_canary_ids(transcript: List[Dict[str, Any]]) -> List[str]:
    """
    Walk a closed-loop transcript and collect every canary_id visible in
    router responses, disinformation payloads, and reasoning text.

    Returns a deduplicated list of canary IDs in encounter order.
    """
    seen: dict[str, None] = {}  # ordered dedup
    for step in transcript:
        # Router response fields
        rr = step.get("router_response") or {}
        for val in rr.values():
            if isinstance(val, str):
                for m in _CANARY_PATTERN.findall(val):
                    seen[m] = None
            elif isinstance(val, dict):
                for v2 in val.values():
                    if isinstance(v2, str):
                        for m in _CANARY_PATTERN.findall(v2):
                            seen[m] = None

        # LLM decision reasoning (agent may echo canary IDs)
        dec = step.get("llm_decision") or {}
        reasoning = dec.get("reasoning", "")
        if isinstance(reasoning, str):
            for m in _CANARY_PATTERN.findall(reasoning):
                seen[m] = None

    # Also scan the raw JSON dump of the entire step (catches nested keys)
    import json
    raw = json.dumps(transcript)
    for m in _CANARY_PATTERN.findall(raw):
        seen[m] = None

    return list(seen)


def simulate_canary_reuse(
    canary_id: str,
    client: Any,
    *,
    session_id: Optional[str] = None,
) -> Dict[str, Any]:
    """
    POST a simulated canary reuse event to Seraph.

    Parameters
    ----------
    canary_id   : The canary ID extracted from a transcript.
    client      : A client supporting ``.post(path, json=payload)``
    session_id  : Optional replay session ID (generated if not provided).

    Returns
    -------
    dict with keys: canary_id, status_code, alert_fired, response_body, error
    """
    replay_session = session_id or f"canary-replay-{str(uuid.uuid4())[:8]}"
    payload = {
        "canary_id": canary_id,
        "session_id": replay_session,
        "source": "external_canary_replay_test",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    try:
        resp = client.post(_CANARY_VERIFY_PATH, json=payload)
        status = resp.status_code
        body: Dict[str, Any]
        try:
            body = resp.json()
        except Exception:
            body = {"raw": resp.text if hasattr(resp, "text") else ""}

        # Determine whether an alert fired — the endpoint should return
        # {"alert": true, ...} or {"route": "trap_sink"} / HTTP 200 + alert field.
        alert_fired = bool(
            body.get("alert")
            or body.get("canary_alert")
            or body.get("route") in {"trap_sink", "honeypot", "canary_alert"}
            or status == 200
        )
        return {
            "canary_id": canary_id,
            "status_code": status,
            "alert_fired": alert_fired,
            "response_body": body,
            "error": None,
        }
    except Exception as exc:  # noqa: BLE001
        return {
            "canary_id": canary_id,
            "status_code": None,
            "alert_fired": False,
            "response_body": {},
            "error": str(exc),
        }


def run_canary_replay_verification(
    records: List[Dict[str, Any]],
    client: Any,
    *,
    verbose: bool = False,
) -> Dict[str, Any]:
    """
    Extract all canary IDs from a list of engagement payloads, simulate external
    reuse of each, and return an aggregate verification report.

    Parameters
    ----------
    records   : List of engagement payloads (each has ``closed_loop_transcript``)
    client    : Seraph client compatible with ``simulate_canary_reuse()``
    verbose   : Print progress

    Returns
    -------
    dict with:
        canary_ids_found    : total unique canary IDs extracted
        replays_attempted   : number of reuse simulations
        alerts_fired        : how many triggered an alert
        alert_rate          : fraction that triggered alerts
        no_real_mapping     : bool (True if no canary ID returned non-deception data)
        results             : per-canary result list
    """
    all_canary_ids: dict[str, None] = {}
    for payload in records:
        transcript = payload.get("closed_loop_transcript", [])
        for cid in extract_canary_ids(transcript):
            all_canary_ids[cid] = None

    unique_ids = list(all_canary_ids)
    if verbose:
        print(f"[canary_replay] found {len(unique_ids)} unique canary IDs")

    results: List[Dict[str, Any]] = []
    alerts = 0
    real_mapping_detected = False

    for cid in unique_ids:
        result = simulate_canary_reuse(cid, client)
        results.append(result)
        if result["alert_fired"]:
            alerts += 1
        # If any canary returned data that looks real (non-deception routes),
        # flag it as a potential data exposure.
        body = result.get("response_body", {})
        if body.get("route") not in (None, "trap_sink", "honeypot", "canary_alert", "unknown"):
            real_mapping_detected = True
        if verbose:
            status = "ALERT" if result["alert_fired"] else "miss"
            print(f"  [{status}] {cid}  HTTP {result['status_code']}")

    n = len(unique_ids)
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "canary_ids_found": n,
        "replays_attempted": n,
        "alerts_fired": alerts,
        "alert_rate": round(alerts / max(1, n), 4),
        "no_real_mapping": not real_mapping_detected,
        "passed": alerts == n and not real_mapping_detected,
        "results": results,
    }
