FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        iproute2 \
        iputils-ping \
        iptables \
        nftables \
        tcpdump \
        wireguard-tools \
    && rm -rf /var/lib/apt/lists/*

CMD ["sleep", "infinity"]
